import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    // Tài liệu kỹ thuật sidebar
    technicalDocumentationSidebar: [
        {
            type: 'autogenerated',
            dirName: '00-giai-phap-cong-nghe/02-tai-lieu-ky-thuat'
        }
    ],
};

export default sidebars;
