import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
    // Tài liệu kỹ thuật sidebar
    technicalDocumentationSidebar: [
        {
            type: 'autogenerated',
            dirName: '00-giai-phap-cong-nghe/02-tai-lieu-ky-thuat'
        }
    ],
    apiSidebar: [
        {
            type: "category",
            label: "THỬ NGHIỆM API",
            link: {
                type: "generated-index",
                title: "THỬ NGHIỆM API",
                description: "Tài liệu API chi tiết và công cụ thử nghiệm trực tiếp",
                slug: "/api"
            },
            items: apiSidebar
        }
    ]
};

export default sidebars;
